import jsPDF from "jspdf";

function DownloadReport({ result }) {
  const downloadPDF = () => {
    const doc = new jsPDF();

    // =========================
    // Title
    // =========================
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(30, 64, 175);
    doc.text("AI Resume Analyzer Report", 20, 20);

    doc.setDrawColor(59, 130, 246);
    doc.line(20, 25, 190, 25);

    // Date
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(
      `Generated: ${new Date().toLocaleString()}`,
      20,
      32
    );

    // =========================
    // Scores
    // =========================

    doc.setFontSize(16);
    doc.setTextColor(0);

    doc.text("ATS Score", 20, 45);
    doc.text(`${88}%`, 160, 45);

    doc.text("Match Score", 20, 55);
    doc.text(`${result.match_score}%`, 160, 55);

    let y = 70;

    // =========================
    // Matched Skills
    // =========================

    doc.setFont("helvetica", "bold");
    doc.setTextColor(34, 197, 94);
    doc.text("Matched Skills", 20, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(0);

    result.matched_skills?.forEach((skill) => {
      doc.text(`• ${skill}`, 25, y);
      y += 7;
    });

    y += 6;

    // =========================
    // Missing Skills
    // =========================

    doc.setFont("helvetica", "bold");
    doc.setTextColor(239, 68, 68);

    doc.text("Missing Skills", 20, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(0);

    result.missing_skills?.forEach((skill) => {
      doc.text(`• ${skill}`, 25, y);
      y += 7;
    });

    y += 6;

    // =========================
    // Strengths
    // =========================

    doc.setFont("helvetica", "bold");
    doc.setTextColor(22, 163, 74);

    doc.text("Strengths", 20, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(0);

    result.strengths?.forEach((item) => {
      doc.text(`• ${item}`, 25, y);
      y += 7;
    });

    y += 6;

    // =========================
    // Weaknesses
    // =========================

    doc.setFont("helvetica", "bold");
    doc.setTextColor(220, 38, 38);

    doc.text("Weaknesses", 20, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(0);

    result.weaknesses?.forEach((item) => {
      doc.text(`• ${item}`, 25, y);
      y += 7;
    });

    y += 6;

    // =========================
    // Recommendations
    // =========================

    doc.setFont("helvetica", "bold");
    doc.setTextColor(37, 99, 235);

    doc.text("Recommendations", 20, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(0);

    result.recommendations?.forEach((item) => {
      doc.text(`• ${item}`, 25, y);
      y += 7;
    });

    // =========================
    // Footer
    // =========================

    doc.setFontSize(10);
    doc.setTextColor(120);

    doc.text(
      "Generated by AI Resume Analyzer",
      20,
      285
    );

    doc.save("AI_Resume_Report.pdf");
  };

  return (
    <div className="flex justify-center mt-10">
      <button
        onClick={downloadPDF}
        className="bg-purple-600 hover:bg-purple-700 transition-all duration-300 text-white font-bold px-10 py-4 rounded-xl shadow-xl hover:scale-105"
      >
        📄 Download Professional PDF Report
      </button>
    </div>
  );
}

export default DownloadReport;